### PR TITLE
Nik api integration with node

### PR DESCRIPTION
**Pull request by wirednkod**
Solves #65

### CODE REVIEW

**Comment by raoulmillais** [comment]
I'm getting this error in the chrome devtools on the homepage:
```
16:28:52.811 Error: system.account(AccountId) is a map, requiring 1 argument, 0 found
    at assert (assert.js:34)
    at doMap (validate.js:33)
    at extractStorageArgs (validate.js:46)
    at decorateMethod.methodName (Decorate.js:414)
    at index.js:86
    at new Promise (<anonymous>)
    at decorateSubscribe (index.js:82)
    at Object.account (index.js:101)
    at useUserInfo.ts:19
    at invokePassiveEffectCreate (react-dom.development.js:23487)
```

**Comment by wirednkod** [comment]
- Refactored and use correctly the AccountContext (and relevant types/hooks) in order to retrieve and save from/to localStorage in an easy way.
- Added extra checks for account not to break in case it is deleted from localStorage
- Fix Burn
- Remove unnecessary passing of functions from parent -> child components
- Added custom "units" that are retrieved from chain or defaults to 'Unit'

**Comment by raoulmillais** [comment]
> I'm getting this error in the chrome devtools on the history page:
> 
> ```
> 16:28:52.811 Error: system.account(AccountId) is a map, requiring 1 argument, 0 found
>     at assert (assert.js:34)
>     at doMap (validate.js:33)
>     at extractStorageArgs (validate.js:46)
>     at decorateMethod.methodName (Decorate.js:414)
>     at index.js:86
>     at new Promise (<anonymous>)
>     at decorateSubscribe (index.js:82)
>     at Object.account (index.js:101)
>     at useUserInfo.ts:19
>     at invokePassiveEffectCreate (react-dom.development.js:23487)
> ```

I can't reproduce this again now :thinking:

**Comment by raoulmillais** [comment]
I see "undefined" instead of the name of the unit in the history page:

**Comment by wirednkod** [comment]
> I see "undefined" instead of the name of the unit in the history page:
> 
> 

This is not fixed yet - will be fixed with issues #66 #67

**Comment by wirednkod** [comment]
> > I'm getting this error in the chrome devtools on the history page:
> > ```
> > 16:28:52.811 Error: system.account(AccountId) is a map, requiring 1 argument, 0 found
> >     at assert (assert.js:34)
> >     at doMap (validate.js:33)
> >     at extractStorageArgs (validate.js:46)
> >     at decorateMethod.methodName (Decorate.js:414)
> >     at index.js:86
> >     at new Promise (<anonymous>)
> >     at decorateSubscribe (index.js:82)
> >     at Object.account (index.js:101)
> >     at useUserInfo.ts:19
> >     at invokePassiveEffectCreate (react-dom.development.js:23487)
> > ```
> 
> I can't reproduce this again now 🤔

This was happening during some localstorage corruption. If you pull latest and clean localStorage this hopefully will not exist

**Comment by raoulmillais** [comment]
> > > I'm getting this error in the chrome devtools on the history page:
> > > ```
> > > 16:28:52.811 Error: system.account(AccountId) is a map, requiring 1 argument, 0 found
> > >     at assert (assert.js:34)
> > >     at doMap (validate.js:33)
> > >     at extractStorageArgs (validate.js:46)
> > >     at decorateMethod.methodName (Decorate.js:414)
> > >     at index.js:86
> > >     at new Promise (<anonymous>)
> > >     at decorateSubscribe (index.js:82)
> > >     at Object.account (index.js:101)
> > >     at useUserInfo.ts:19
> > >     at invokePassiveEffectCreate (react-dom.development.js:23487)
> > > ```
> > 
> > 
> > I can't reproduce this again now thinking
> 
> This was happening during some localstorage corruption. If you pull latest and clean localStorage this hopefully will not exist

Ideally this shouldn't error.  Maybe do a sanity check on the contents of localStorage, clear it if it is in the wrong format and log a warning?

**Review by raoulmillais — COMMENTED** [review]
Apart from the error in the console when the local storage when it's the wrong format this LGTM :+1: I'm out of touch with react so I can't review properly for best practices and use of react though.

**Pull request merged**
