### PR TITLE
Βump smoldot version to 0.2.8

### PR DESCRIPTION
**Pull request by wirednkod**

### CODE REVIEW

**Review by raoulmillais — CHANGES_REQUESTED** [review]
why only in the test utils and extension?  surely we should bump in @substrate/connect too?

**Comment by wirednkod** [comment]
@substrate/connect was bumped [here](https://github.com/paritytech/substrate-connect/pull/324/files#diff-c503ada501a08565c380a3a344b61b1927e844c73021888e7cdde350309b8cec) but not the rest.

**Comment by wirednkod** [comment]
As soon as there is a new version I altered this PR from 0.2.6 on 2 workspaces to 0.2.8 for all workspaces

**Comment by raoulmillais** [comment]
This is no longer valid.  PR open for smoldot 0.29.0

**Pull request closed without merging**
