### PR TITLE
Fix waiting for health check from smoldot to be reliable by using 'sh…

### LINKED ISSUE #284: alter indication of "connected" to smoldot
Once https://github.com/paritytech/smoldot/issues/720 is implemented a callback will be added, that will be triggered after smoldot have finished syncing.

We need to alter SmoldotProvider in order to wait for this callback to be called in order to "know" that we are connected.

Issue is understandable now - as before smoldot finish syncing, substrate-connect assumes that connection is established and an error appears:
```
RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32000: Storage query errors:
- TrieRootNotFound
................
emit @ SmoldotProvider.js:341
(anonymous) @ SmoldotProvider.js:170
Promise.then (async)
(anonymous) @ SmoldotProvider.js:178
setInterval (async)
connect @ SmoldotProvider.js:198
Show 8 more frames

```

### PR DESCRIPTION
**Pull request by wirednkod**
…ouldHavePeers' and 'isSyncing' of health; Fixes #284

### CODE REVIEW

**Review by raoulmillais — CHANGES_REQUESTED** [review]
The new branches in the if statement definitely need to be covered by tests. It should be easy to adapt an existing one by changing the mocked health response and checking it does the right thing

**Comment by wirednkod** [comment]
> The new branches in the if statement definitely need to be covered by tests. It should be easy to adapt an existing one by changing the mocked health response and checking it does the right thing

Tests will be written once all open branches are merged (including this). Then we can finish with the coverage. I dont want to continue the chain of opening branches right now - until all pending once are merged.

**Comment by raoulmillais** [comment]
We agreed to this months ago. Tests don't need a new branch. In fact they *shouldn't* be on a different branch. You've changed code that was nearly 100% covered by tests, so you should not merge this until you have added and adapted tests to account for the changes in behaviour. It is literally the core of what we're delivering.

**Comment by wirednkod** [comment]
This part of the code will be covered once all merges are finished. The reason why I am say this, is that 3 pending PRs are having major changes on tests (new additions/corrections and increased code coverage) while they are still not merged to master, while this is minor change straight to master branch. In case tests are written on this branch then there will be severe conflicts with rest of branches which I would prefer to avoid. As a result, the tests will be written once all 4 PRs are merged. Its anyways in the road map to have coverage as much as possible (that is what we agreed on).

**Comment by wirednkod** [comment]
Closing this PR and will reopen it as a chain PR from #282 is order to write the tests that are immediately needed.

**Pull request closed without merging**
