### PR TITLE
Remove sending the relay chain name to the extension

### PR DESCRIPTION
**Pull request by tomaka**
This removes passing the `relayChainName` from the foreground to the extension. Which relay chain a parachain should connect to is already found in the chain specification, so there's no need to additionally pass the same value as a separate parameter.

I've noticed that the `connect` method of the detector is broken, but it's already broken before this PR and can be fixed afterwards.

### CODE REVIEW

**Review by wirednkod — COMMENTED** [review]
@tomaka Extension needs to know the correlation between relayChain and parachain for the Options page - in order to show the structure (which parachain is connected to which chain).
In addition - once healthcheck is merged - based on #451 the networks must be updated as unique and have the correlation with the parachains instead of the current structure

**Comment by tomaka** [comment]
> Extension needs to know the correlation between relayChain and parachain for the Options page - in order to show the structure (which parachain is connected to which chain).

The relay chain ID can be found in the `relay_chain` field of the chain specification of a parachain, there's no need to pass it a second time. Example: https://github.com/paritytech/smoldot/blob/88ff678048378c6b61e9087fffe1278c6e26be34/bin/westend-westmint.json#L13

**Comment by wirednkod** [comment]
[Here](https://github.com/paritytech/substrate-connect/pull/475/files#diff-05bb44f78f8c40ea612398108dccd416ffc760bff6f63cfcd50e83b320948de3R200) all chains that exist in network are mapped as potentialRelayChains even if this is a relayChain. I have understood from the [gist](https://gist.github.com/tomaka/764fa8f9f51cddabfb616b37d536340a) that this was needed only for parachain and not for relay ones. I assume based on the code here that smoldot will understand the relay chain and will not use the `potentialRelayChains` field. If thats the case then this lgtm.

**Review by raoulmillais — CHANGES_REQUESTED** [review]
Can you fix the linting errors please?

**Comment by tomaka** [comment]
Done

**Review by raoulmillais — APPROVED** [review]
LGTM :+1: Feel free to merge.  Btw, I noticed your commit message said "Maybe fix lints". You can check locally with `yarn lint`

**Pull request merged**
