### PR TITLE
upgrade dependencies

### PR DESCRIPTION
**Pull request by josepot**

### CODE REVIEW

**Review by wirednkod — APPROVED** [review]

**Comment by wirednkod** [comment]
@josepot please update the substrate-connect CHANGELOG with a link to the smoldot CHANGELOG, for the upgrade of smoldotto 0.6.5

**Comment by josepot** [comment]
> @josepot please update the substrate-connect CHANGELOG with a link to the smoldot CHANGELOG, for the upgrade of smoldotto 0.6.5

Unfortunately I can't publish new versions on npm. So, whenever we do publish the next patch, we should then update the CHANGELOG and not before.

**Comment by josepot** [comment]
> > > @josepot please update the substrate-connect CHANGELOG with a link to the smoldot CHANGELOG, for the upgrade of smoldotto 0.6.5
> > 
> > 
> > Unfortunately I can't publish new versions on npm. So, whenever we do publish the next patch, we should then update the CHANGELOG and not before.
> 
> CHANGELOG should be updated for each PR - there is an `## Unreleased` section which can change to the new version once we push the new version

Right, sorry, I misunderstood... I thought that you meant "releasing" :facepalm: , yep for sure, I will update the changelog, thanks!

**Comment by josepot** [comment]
> Could you revert the version of smoldot to the one before this PR?

Done!

**Pull request merged**
