### PR TITLE
re-add the web-ext dev dependency

### PR DESCRIPTION
**Pull request by wirednkod**

### CODE REVIEW

**Comment by josepot** [comment]
Out of curiosity: where and how is `web-ext` being used?

**Comment by wirednkod** [comment]
For running chrome and mozilla extension
https://github.com/paritytech/substrate-connect/blob/master/projects/extension/package.json#L18

**Comment by josepot** [comment]
> For running extension in chrome and mozilla (without having to add it from dev tools - extremelly helpful especially for mozilla) https://github.com/paritytech/substrate-connect/blob/master/projects/extension/package.json#L18

Got it, thanks! So, since this dependency is very specific to the `extension`, could we please just add it in the `package.json` of its own workspace?

**Comment by wirednkod** [comment]
Sure. Though its a dev dependency. I thought all of them can be on root package

**Comment by josepot** [comment]
> Sure. Though its a dev dependency. I thought all of them can be on root package

All the common ones, yes

**Review by josepot — APPROVED** [review]

**Pull request merged**
